name: Elixir Build PLTs

on:
  push:
    branches:
      - main

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    strategy:
      matrix:
        elixir: [
          1.10.3,
          1.11.0,
          1.12.0
        ]
        otp: [
          22.3,
          23.1,
          24.0
        ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Elixir
        uses: actions/setup-elixir@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}
      - name: Install dependencies
        run: mix deps.get
      - name: mix dialyzer
        run: mix dialyzer
