name: Build Branches

on:
  push:
    branches:
      - main
  schedule:
    - cron:  '*/10 * * * *'

jobs:
  versions:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PERSONAL_GITHUB_ACCESS_TOKEN }}
          persist-credentials: false
      - run: .github/scripts/versions.sh
        env:
          GITHUB_EMAIL: ${{ secrets.EMAIL }}
          GITHUB_NAME: ${{ secrets.NAME }}
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_ACCESS_TOKEN }}
